### ISSUE TITLE
维度维度

### ISSUE THREAD

**Issue by adzhua** [CyberZHG/keras-piecewise-pooling#2]
您好，我在使用PiecewisePooling1D时，进行到model.fit这不总是报：“tensorflow.python.framework.errors_impl.InvalidArgumentError: Matrix size-incompatible”错误，我就是在PiecewisePooling1D后加了一些层，类似如下：
maxpool_0 = PiecewisePooling1D(pool_type=PiecewisePooling1D.POOL_TYPE_MAX)([conv_0, piece_input])
flatten = Flatten()(maxpool_0 )
dropout = Dropout(drop)(flatten)
output = Dense(units=9, activation='softmax')(dropout)
假如我把PiecewisePooling1D换成MaxPool1D就没有问题，能否解答下

**Comment by CyberZHG** [comment]
Please provide a minimal code example that reproduces the error you encountered.

**Comment by adzhua** [comment]
when I run the demo you gave in tensorfow-gpu 1.4.0, I gave another error:
Traceback (most recent call last):
  File "F:/codes/my_re/cnns/test.py", line 12, in <module>
    pool_layer = PiecewisePooling1D(pool_type=PiecewisePooling1D.POOL_TYPE_AVERAGE)([data_input, position_input])
  File "E:\Program Files\Python36\lib\site-packages\keras\engine\topology.py", line 603, in __call__
    output = self.call(inputs, **kwargs)
  File "E:\Program Files\Python36\lib\site-packages\keras_piecewise\piecewise.py", line 31, in call
    positions = K.concatenate([K.zeros((K.shape(inputs)[0], 1), dtype='int32'), positions], axis=1)
  File "E:\Program Files\Python36\lib\site-packages\keras\backend\tensorflow_backend.py", line 680, in zeros
    return variable(tf.constant_initializer(0., dtype=tf_dtype)(shape),
  File "E:\Program Files\Python36\lib\site-packages\tensorflow\python\ops\init_ops.py", line 200, in __call__
    self.value, dtype=dtype, shape=shape, verify_shape=verify_shape)
  File "E:\Program Files\Python36\lib\site-packages\tensorflow\python\framework\constant_op.py", line 208, in constant
    value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "E:\Program Files\Python36\lib\site-packages\tensorflow\python\framework\tensor_util.py", line 380, in make_tensor_proto
    if shape is not None and np.prod(shape, dtype=np.int64) == 0:
  File "E:\Program Files\Python36\lib\site-packages\numpy\core\fromnumeric.py", line 2518, in prod
    out=out, **kwargs)
  File "E:\Program Files\Python36\lib\site-packages\numpy\core\_methods.py", line 35, in _prod
    return umr_prod(a, axis, dtype, out, keepdims)
ValueError: setting an array element with a sequence.

**Comment by adzhua** [comment]
the first error I encountered is with code as following:
`piece_input = Input(shape=(3,), dtype='int32', name='piece_input')  

w_inputs = Input(shape=(sequence_length,), dtype='int32', name='w_inputs')
w_embedding = Embedding(input_dim=vocabulary_size, output_dim=embedding_dim, input_length=sequence_length, weights=[vec], name='w_embedding')(w_inputs)

conv_0 = Conv1D(num_filters, kernel_size=filter_sizes[0], padding='same', kernel_initializer='normal', activation='relu')(w_embedding)
maxpool_0 = PiecewisePooling1D(pool_type=PiecewisePooling1D.POOL_TYPE_MAX)([conv_0, piece_input])

flatten = Flatten()(maxpool_0)
dropout = Dropout(drop)(flatten)
output = Dense(units=9, activation='softmax')(dropout)

model = Model(inputs=[piece_input, w_inputs], outputs=output)

adam = Adam(lr=1e-4, beta_1=0.9, beta_2=0.999, epsilon=1e-08, decay=0.0)
model.compile(optimizer=adam, loss=losses.categorical_crossentropy)

print(model.predict([train_pos, train_sentences]).tolist())
`

**Comment by adzhua** [comment]
whether has some errors in function compute_output_shape?

**Comment by CyberZHG** [comment]
I'm not able to reproduce the error with the following code:

```python
import keras
import numpy as np
from keras.layers import Input, Embedding, Conv1D, Flatten, Dropout, Dense
from keras_piecewise_pooling import PiecewisePooling1D

sequence_length = 13
vocabulary_size = 7
embedding_dim = 5
num_filters = 17

piece_input = Input(shape=(3,))

w_inputs = Input(shape=(sequence_length,))
w_embedding = Embedding(
    input_dim=vocabulary_size,
    output_dim=embedding_dim,
)(w_inputs)

conv_0 = Conv1D(
    num_filters,
    kernel_size=3,
)(w_embedding)
maxpool_0 = PiecewisePooling1D(
    pool_type=PiecewisePooling1D.POOL_TYPE_MAX,
)([conv_0, piece_input])

flatten = Flatten()(maxpool_0)
dropout = Dropout(0.1)(flatten)
output = Dense(units=9, activation='softmax')(dropout)

model = keras.models.Model(inputs=[piece_input, w_inputs], outputs=output)

model.compile(optimizer='adam', loss='categorical_crossentropy')
model.summary()

batch_size = 16
train_pos = np.asarray([[5, 9, 12], [2, 4, 7]] * (batch_size // 2))
train_sentences = np.random.randint(
    low=0,
    high=vocabulary_size - 1,
    size=(batch_size, sequence_length),
)
print(model.predict([train_pos, train_sentences]))
```

Are you using the latest version of the repo?

**Comment by adzhua** [comment]
thank you, it works well now after i reinstalled keras_piecewise
